update behaviour to not move to destination collection after collection ops
ente-io/photos-web pull request #1556
Opened 2024-01-18 01:39 UTC by abhinavkgrd

## Description

^ title 

fixes #1554 

## Test Plan

tested locally

2024-01-18 07:22 UTC, 0nullpointer requested changes
Currently whenever you are moving the last item from the collection the user is in an in-between state. Maybe move them to the gallery (All) screen? 
<img width="1470" alt="Screenshot 2024-01-18 at 12 51 44" src="https://github.com/ente-io/photos-web/assets/126418158/07b0a4a9-d457-4a5c-ae32-086a3ca6b634">

2024-01-22 10:10 UTC, abhinavkgrd commented on apps/photos/src/pages/gallery/index.tsx
> +                        setActiveCollectionID(ALL_SECTION);
yes , this the fix for the issue
> Currently whenever you are moving the last item from the collection the user is in an in-between state. Maybe move them to the gallery (All) screen?

2024-01-22 10:38 UTC, ua741 submitted a review, later dismissed

2024-01-22 10:45 UTC, ua741 commented on apps/photos/src/pages/gallery/index.tsx
> +                        setActiveCollectionID(ALL_SECTION);
should we add a comment, redirect to ALL as no items is left in the collection?

2024-01-24 03:10 UTC, ua741 approved these changes

2024-01-24 05:51 UTC, 0nullpointer approved these changes

2024-01-24 05:51 UTC, merged